//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RenameIt.rc
//
#define IDC_STATUS_BAR                  10
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RENAMEIT_DIALOG             102
#define IDS_ADDDIR                      102
#define IDS_CANTSAVE                    103
#define IDS_GENERICERROR                104
#define ID_CANT_SAVE_FILE               105
#define ID_OVERWRITE_SYSTEM_FILE        106
#define ID_OVERWRITE_READONLY_FILE      107
#define IDS_RENAME_SYSTEM_FILE          108
#define IDS_CONFIRM_EXIT                109
#define IDS_REPORT_BEFORE               110
#define IDS_MANUAL_RENAMING_ERROR       111
#define IDS_NO_FILENAME_CHANGES         112
#define IDS_RENAMED_ALL                 113
#define IDS_CRITICAL_ERROR              114
#define IDS_DONE                        115
#define IDS_BEFORE                      116
#define IDS_AFTER                       117
#define IDS_FILTER                      118
#define IDS_NO_RECENT_FILTERS           119
#define IDS_RECENT_FILTERS              120
#define IDS_OPEN                        121
#define IDS_SAVE_AS                     122
#define IDS_CANT_OPEN_FILTERS           123
#define IDS_SAMPLE_PATH                 124
#define IDS_HOME_PAGE                   125
#define IDS_MENU_ADD_FILTER             126
#define IDS_MENU_MOVE_UP                127
#define IDR_MAINFRAME                   128
#define IDS_MENU_MOVE_DOWN              128
#define IDS_MENU_REMOVE                 129
#define IDS_MENU_REMOVE_ALL             130
#define IDS_MENU_PROPERTIES             131
#define IDS_FILTERS                     132
#define IDS_MENU_ADD_FOLDER             133
#define IDS_MENU_ADD_FILES              134
#define IDR_MAINMENU                    135
#define IDS_FILES                       135
#define IDR_SEARCH_REGEXP               136
#define IDS_RENAMING_CANCELED           136
#define IDS_ERROR                       137
#define IDS_REMOVED_FROM_DISK           138
#define IDS_CONFLICT_WITH_EXISTING      139
#define IDS_CANNOT_RENAME_MISSING       140
#define IDS_MENU_RENAME                 141
#define IDS_MENU_REMOVE_MISSING         142
#define IDS_MENU_REFRESH                143
#define IDS_RENAME_LIST                 144
#define IDS_FILE_ALREADY_EXIST          145
#define IDS_NOT_EMPTY_FILTER_LIST_SAVE  146
#define IDS_CANT_SAVE_FILTERS           147
#define IDS_MENU_SELECT_ALL             148
#define IDS_MENU_SELECT_NONE            149
#define IDS_MENU_SELECT_INVERT          150
#define IDD_CONFIGURE                   151
#define IDS_REPORT_ERROR_REMAIN         151
#define IDS_MODIFY_EXTENSION_WARNING    152
#define IDS_NO_FILTER                   153
#define IDS_SCAN_FOR_PLUGINS            154
#define IDC_LINK_CURSOR                 155
#define IDS_UNABLE_TO_LOAD_PLUGIN       155
#define IDS_ERROR_LOADING_PLUGIN        156
#define IDS_UNKNOWN                     157
#define IDS_COLUMN_FILE_NAME            158
#define IDS_COLUMN_ERROR_MESSAGE        159
#define IDS_REPORT_ERROR_DETECTED       160
#define IDS_RIT_OFN_FILTER              161
#define IDB_DEL                         162
#define IDS_FILES_OFN_FILTER            162
#define IDB_DOWN                        163
#define IDS_FILES_OFN_TITLE             163
#define IDB_ADDFILTER                   164
#define IDS_FOLDER_OFN_TITLE            164
#define IDB_PROP                        165
#define IDS_UNKNOWN_FILTER              165
#define IDB_UP                          166
#define IDS_STATUS_RENAME_COUNT         166
#define IDS_INVALID_FILE_NAME           167
#define IDB_SAVE                        168
#define IDS_RENAME_PARTS                168
#define IDB_OPEN                        169
#define IDS_TT_SELECT_RENAME_PARTS      169
#define IDS_NO_FILTER_TO_SAVE           170
#define IDB_ADDFOLDER                   171
#define IDS_CONFLICT_SAME_AFTER         171
#define IDS_RISKY_FNAME_TOO_LONG        172
#define IDB_ADDFILES                    173
#define IDS_EMPTY_FILE_NAME             173
#define IDS_RISKY_FNAME_RESERVED        174
#define IDS_RISKY_FNAME_TRIM_SPACES     175
#define IDD_REPORT                      176
#define IDS_LONGUER_THAN_MAX_PATH       176
#define IDS_START_END_BACKSLASH_MISSING 177
#define IDS_INVALID_DIRECTORY_NAME      178
#define IDI_REMOVED                     179
#define IDS_EMPTY_DIRECTORY_NAME        179
#define IDS_RISKY_DIRNAME_RESERVED      180
#define IDI_REN_OK                      181
#define IDS_RISKY_DIRNAME_TRIM_SPACES   181
#define IDI_CONFLICT                    182
#define IDS_INCONSISTENT_DIRECTORY_CASE 182
#define IDI_BADNAME                     183
#define IDS_RISKY_DIRNAME_TOO_LONG      183
#define IDS_IN_USE                      184
#define IDB_DELALL                      185
#define IDS_CANNOT_CHANGE_ROOT          185
#define IDR_SEARCH_WILD                 187
#define ID_TAGGETBYSTAR                 191
#define IDI_REN_ERROR                   194
#define IDD_NOT_ADDED_FILES             195
#define IDD_RENAME                      197
#define IDB_UNSELECT_ALL                198
#define IDB_INVERSE_SELECTION           199
#define IDB_SELECT_ALL                  200
#define IDI_INVALIDNAME                 202
#define IDD_RENAME_ERROR                203
#define IDI_WIN_ERROR                   204
#define IDD_PROGRESS                    205
#define IDR_FILTERS_MENU                206
#define IDR_FILTERS_TOOLBAR             212
#define IDD_WIZ_CASE                    215
#define IDD_WIZ_CROP                    216
#define IDD_WIZ_ID3TAG                  217
#define IDD_WIZ_APPEND                  218
#define IDD_WIZ_ENUM                    219
#define IDD_RENAMING_PROGRESS           220
#define IDC_SERIES_CHECK                1000
#define IDS_SEARCH_AND_REPLACE          1000
#define IDC_SERIES_BUTTON               1001
#define IDS_DESCR_ID3                   1001
#define IDC_ID3TAG_CHECK                1002
#define IDS_SERIES_HELP                 1002
#define IDC_FILENAMES_IN                1003
#define IDC_SERIE_START_EDIT            1003
#define IDR_REPLACE                     1003
#define IDS_SEARCH_INVITE               1003
#define IDC_CROPCOUNT_SPIN              1003
#define IDC_RULES_LIST                  1004
#define IDC_SERIE_STEP_EDIT             1004
#define IDS_REPLACE_INVITE              1004
#define IDC_CROPSTARTFROM_SPIN          1004
#define IDI_RENAMER                     1005
#define IDS_DESCR_REPLACE_REGEXP        1005
#define IDC_WHOLE_TEXT                  1006
#define IDD_SEARCH_REPLACE_DIALOG       1006
#define IDS_DESCR_REPLACE_WILDCARD      1006
#define IDC_BUTTON_ADDRULE              1007
#define IDC_MATCHCASE                   1007
#define IDS_DESCR_REPLACE               1007
#define IDC_INVERT_CHECK                1007
#define IDC_BUTTON_ADDFILE              1008
#define IDC_SEARCHBUTTON                1008
#define IDS_DESCR_WITH                  1008
#define IDS_DESCR_MATCH_CASE            1009
#define IDC_BUTTON_REMOVERULE           1010
#define IDC_REPLACEBUTTON               1010
#define IDS_DESCR_SKIP_CASE             1010
#define IDC_BUTTON_FILTERLIST           1011
#define IDC_WHOLEWORD_TEXT              1011
#define IDS_DESCR_ONCE                  1011
#define IDC_BUTTON_CLEARRULE            1012
#define IDC_SERIE_START_SPIN            1012
#define IDS_DESCR_SERIES                1012
#define IDC_SERIE_STEP_SPIN             1013
#define IDS_SERIES_DEFAULT_REPLACE      1013
#define IDC_BUTTON_ADDFILTER2           1013
#define IDC_BUTTON_ADDFOLDER            1014
#define IDS_DESCR_WHOLE_TEXT            1014
#define IDS_TT_BEFORE                   1015
#define IDS_TT_AFTER                    1016
#define IDS_TT_ID3                      1017
#define IDS_TT_ONCE                     1019
#define IDC_NATURALCASE                 1020
#define IDC_NAMECASE                    1021
#define IDC_LOWERCASE                   1022
#define IDC_UPPERCASE                   1023
#define IDC_INVERTCASE                  1024
#define IDC_CROPCOUNT                   1025
#define IDC_USE_CHECK                   1029
#define IDC_CASE_CHECK                  1030
#define IDC_BEFORE                      1037
#define IDC_AFTER                       1038
#define IDC_SMARTCROP                   1040
#define IDC_CROPSTARTFROM               1042
#define IDC_STATIC_RULES                1052
#define IDC_EDIRECTORY                  1063
#define IDC_BROWSE                      1064
#define IDC_LEFTSIDE                    1069
#define IDC_RIGHTSIDE                   1070
#define IDC_ID3FORMAT                   1079
#define IDC_WEB_EDIT                    1082
#define IDC_REPORT_LIST                 1091
#define IDC_NEW_EDIT                    1094
#define IDC_ORIGINAL_EDIT               1095
#define IDC_USE_COMBO                   1096
#define IDC_CASE_COMBO                  1097
#define IDC_STATUS_STATIC               1100
#define IDC_LIST                        1102
#define IDC_BUTTON_MOVEUP               1105
#define IDC_BUTTON_MOVEDOWN             1106
#define IDC_RENAMEPART_RICHEDIT         1115
#define IDC_AUTO_ADD_RENAMER_CHECK      1119
#define IDC_ACTION_RADIO                1121
#define IDC_ACTION2_RADIO               1122
#define IDC_DETAILS_BUTTON              1123
#define IDC_HIDE_DETAILS_BUTTON         1124
#define IDC_ACTION3_RADIO               1125
#define IDC_DESCR_STATIC                1126
#define IDC_PROGRESS                    1128
#define IDC_PROGRESS_STATIC             1129
#define IDC_SEARCH_RICHEDIT             1130
#define IDC_REPLACE_RICHEDIT            1131
#define IDC_DEV_EDIT                    1132
#define IDC_PROGRESS1                   1134
#define IDC_PROGRESS2                   1135
#define IDC_PROGRESS3                   1136
#define IDC_SHOW_ALL_CHECK              1136
#define IDC_REPLACE_ONCE_CHECK          1137
#define IDC_SHOW_ONLY_PROBLEMS_CHECK    1138
#define IDS_CMDLINE_FILTER_FILE_MISSING 2000
#define IDS_CMDLINE_LOG_FILE_MISSING    2001
#define IDS_CMDLINE_NO_FILTER           2002
#define IDS_PGRS_CHECK_CAPTION          3000
#define IDS_PGRS_PREREN_CAPTION         3001
#define IDS_PGRS_RENAMING_CAPTION       3002
#define IDS_PGRS_TITLE                  3004
#define ID_HELP_ABOUT                   32776
#define ID_REPLACE_FILEDIR              32776
#define ID_REPLACE_FILENAME             32777
#define ID_FILE_EXIT                    32778
#define ID_REPLACE_FILEEXT              32778
#define ID_ANYCHARACTER                 32779
#define ID_CHARACTERINRANGE             32780
#define ID_CHARACTERNOTINRANGE          32781
#define ID_BEGINNGINGOFLINE             32782
#define ID_ENDOFLINE                    32783
#define ID_TAGGEDEXPRESSION             32784
#define ID_OR                           32786
#define ID_ID3TAGREADER_ARTIST          32786
#define ID_0ORMOREMATCHES               32787
#define ID_ID3TAGREADER_TRACK           32787
#define ID_1ORMOREMATCHES               32788
#define ID_ID3TAGREADER_TITLE           32788
#define ID_ID3TAGREADER_ALBUM           32789
#define ID_ID3TAGREADER_YEAR            32790
#define ID_ALPHANUMERICCHARACTER        32791
#define ID_ID3TAGREADER_COMMENT         32791
#define ID_ALPHABETICCHARACTER          32792
#define ID_ID3TAGREADER_GENRE           32792
#define ID_DECIMALDIGIT                 32793
#define ID_REGEXP_FINDWHATTEXT          32793
#define ID_REGEXP_TAGGEDEXPRESSION1     32794
#define ID_REGEXP_TAGGEDEXPRESSION2     32795
#define ID_REGEXP_TAGGEDEXPRESSION3     32796
#define ID_REGEXP_TAGGEDEXPRESSION4     32797
#define ID_REGEXP_TAGGEDEXPRESSION5     32798
#define ID_REGEXP_TAGGEDEXPRESSION6     32799
#define ID_REGEXP_TAGGEDEXPRESSION7     32800
#define ID_REGEXP_TAGGEDEXPRESSION8     32801
#define ID_REGEXP_TAGGEDEXPRESSION9     32802
#define ID_SEARCHREGEXP_NEWLINE         32811
#define ID_FILE_CONFIGURE               32816
#define ID_VIEW_ALWAYS_ON_TOP           32819
#define ID_FEEDBACK_BUGREPORT           32820
#define ID_FEEDBACK_INFORMATIONREQUEST  32821
#define ID_FEEDBACK_SUGGESTIONS         32822
#define ID_FILE_SAVEAS                  32825
#define ID_REPLACE_FILTEREDNAME         32832
#define ID_REPLACE_UNFILTEREDNAME       32833
#define ID_WILD_0ORMORE                 32834
#define ID_WILD_1MATCH                  32835
#define ID_FILTERS_SEARCHREPLACE        32840
#define ID_FILTERS_CHANGECASE           32841
#define ID_FILTERS_APPEND               32842
#define ID_FILTERS_CROP                 32843
#define ID_FILTERS_ENUMERATION          32844
#define ID_FILTERS_ID3TAG               32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
